"""Pydantic models. The single source of the schema."""

from manager.models.common import Bbox, LangText
from manager.models.identifiers import (
    ITRS_LEVEL_NUMBER,
    BandLane,
    Difficulty,
    FilterId,
    HeroImage,
    ItrsLevel,
    KeyFigure,
    Maintainer,
    NonMunicipalReason,
    Season,
    SectionType,
    ServiceCategory,
    ServiceSource,
    Surface,
    Traffic,
    WinterMaintenance,
)
from manager.models.project import Feedback, ItrsScales, Project
from manager.models.publish_settings import (
    Frontend,
    HeaderRule,
    PublishSettings,
    Target,
)
from manager.models.published import (
    Catalog,
    CatalogProject,
    NearbyService,
    PublishedMedia,
    PublishedRoute,
    PublishedSegment,
    RouteSummary,
    ServiceGap,
)
from manager.models.route import (
    LEGACY_DIFFICULTY,
    ElevationProfileSection,
    GallerySection,
    HardestSection,
    Itrs,
    MediaInfo,
    Route,
    Section,
    Segment,
    TextSection,
    VideoSection,
)
from manager.models.service import ManualMarker, Service
from manager.models.theme import Colors, Presentation, Theme

__all__ = [
    "ITRS_LEVEL_NUMBER",
    "LEGACY_DIFFICULTY",
    "BandLane",
    "Bbox",
    "Catalog",
    "CatalogProject",
    "Colors",
    "Difficulty",
    "ElevationProfileSection",
    "Feedback",
    "FilterId",
    "Frontend",
    "GallerySection",
    "HardestSection",
    "HeaderRule",
    "HeroImage",
    "Itrs",
    "ItrsLevel",
    "ItrsScales",
    "KeyFigure",
    "LangText",
    "Maintainer",
    "ManualMarker",
    "MediaInfo",
    "NearbyService",
    "NonMunicipalReason",
    "Presentation",
    "Project",
    "PublishSettings",
    "PublishedMedia",
    "PublishedRoute",
    "PublishedSegment",
    "Route",
    "RouteSummary",
    "Season",
    "Section",
    "SectionType",
    "Segment",
    "Service",
    "ServiceCategory",
    "ServiceGap",
    "ServiceSource",
    "Surface",
    "Target",
    "TextSection",
    "Theme",
    "Traffic",
    "VideoSection",
    "WinterMaintenance",
]
